version: "3.7"

services:
  ldaptive:
    image: code.vt.edu:5005/middleware/docker/maven:3.6.0
    volumes:
      - $HOME/.m2:/apps/home/appsadm/.m2
      - $PWD:/apps/ldaptive
    environment:
      - HOST=ldap-test:389
      - BASE_DN=ou=test,dc=vt,dc=edu
      - BIND_DN=uid=1,ou=test,dc=vt,dc=edu
      - BIND_CREDENTIAL=VKSxXwlU7YssGl1foLMH2mGMWkifbODb1djfJ4t2
      - TEST_GROUP=core
      - PROVIDER
    command: bash -c "cd /apps/ldaptive && integration/run"

  ldap-test:
    image: code.vt.edu:5005/middleware/edldap-deploy-env/ldap-test-openldap:latest
    ports:
      - "389:389"
      - "636:636"
      - "88:88"
    logging:
      #driver: "json-file"
      driver: "none"
      options:
        max-size: "100M"
        max-file: "5"
